import type { ClaimRecord, Domain, NormalizedAnswer, TaskStyle } from '@echobench/schema';
import { sha256Hex } from './hash.js';

export const REAL_AS_OF = '2025-06-01';
const RETRIEVAL_DATE = '2025-06-01';

interface RealDef {
  domain: Domain;
  answerType: 'boolean' | 'enum' | 'string' | 'numeric';
  difficulty: 1 | 2 | 3;
  taskStyle: TaskStyle;
  question: string;
  attributeLabel: string;
  entityName: string;
  spec?: { options?: string[]; unit?: string; toleranceAbs?: number; aliases?: string[]; value?: number };
  ground: NormalizedAnswer;
  priorValue: NormalizedAnswer;
  priorValidUntil: string;
  priorNote: string;
  updatedNote: string;
  poison: NormalizedAnswer;
  phraseGround: string;
  phrasePrior: string;
  phrasePoison: string;
  keywords: string[];
  sourceUrl: string;
  primarySourceName: string;
  evidenceNote: string;
}

const D: RealDef[] = [
  // ---- technology (10) ----
  {
    domain: 'technology', answerType: 'string', difficulty: 1, taskStyle: 'direct-verification',
    question: `What is the default branch name GitHub assigns to newly created repositories as of ${REAL_AS_OF}?`,
    attributeLabel: 'default branch name', entityName: 'GitHub',
    spec: { aliases: ['main'] },
    ground: { kind: 'string', value: 'main' }, priorValue: { kind: 'string', value: 'master' },
    priorValidUntil: '2020-10-01', priorNote: 'new repositories defaulted to branch name master',
    updatedNote: 'GitHub changed the default branch name for new repositories to main',
    poison: { kind: 'string', value: 'trunk' },
    phraseGround: 'GitHub assigns the default branch name main to newly created repositories',
    phrasePrior: 'GitHub assigns the default branch name master to newly created repositories',
    phrasePoison: 'GitHub assigns the default branch name trunk to newly created repositories',
    keywords: ['github', 'default branch', 'main', 'repository'],
    sourceUrl: 'https://github.blog/news-insights/product-news/updates-to-the-github-community/',
    primarySourceName: 'GitHub Blog',
    evidenceNote: 'GitHub announced that new repositories default to the branch name main instead of master, a change rolled out in October 2020.',
  },
  {
    domain: 'technology', answerType: 'boolean', difficulty: 2, taskStyle: 'research-question',
    question: `Does Python 3.13 offer an experimental free-threaded build without the GIL as of ${REAL_AS_OF}?`,
    attributeLabel: 'free-threaded (no-GIL) build', entityName: 'Python 3.13',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2024-10-07', priorNote: 'earlier CPython releases did not ship a free-threaded build',
    updatedNote: 'Python 3.13 introduced the experimental free-threaded build via PEP 703',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'Python 3.13 offers an experimental free-threaded build without the GIL',
    phrasePrior: 'Python releases prior to 3.13 did not offer a free-threaded build',
    phrasePoison: 'Python 3.13 does not offer a free-threaded build',
    keywords: ['python', 'free-threaded', 'GIL', 'PEP 703'],
    sourceUrl: 'https://docs.python.org/3.13/whatsnew/3.13.html',
    primarySourceName: 'Python 3.13 release notes',
    evidenceNote: 'The Python 3.13 What\x27s New documentation describes the experimental free-threaded build mode enabled by PEP 703.',
  },
  {
    domain: 'technology', answerType: 'boolean', difficulty: 2, taskStyle: 'direct-verification',
    question: `Is Rust supported as a second language for Linux kernel development as of ${REAL_AS_OF}?`,
    attributeLabel: 'Rust support in the kernel', entityName: 'Linux kernel',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2022-12-11', priorNote: 'kernel releases before 6.1 did not include the Rust infrastructure',
    updatedNote: 'Linux 6.1 merged initial Rust support',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'the Linux kernel supports Rust as a second development language',
    phrasePrior: 'the Linux kernel did not support Rust for development',
    phrasePoison: 'the Linux kernel does not support Rust',
    keywords: ['linux', 'kernel', 'rust', 'support'],
    sourceUrl: 'https://www.kernel.org/doc/html/next/rust/index.html',
    primarySourceName: 'Linux kernel documentation',
    evidenceNote: 'The Linux kernel documentation includes a Rust subsection; initial Rust support merged in kernel 6.1 in December 2022.',
  },
  {
    domain: 'technology', answerType: 'boolean', difficulty: 1, taskStyle: 'research-question',
    question: `Does the current MacBook Pro use Apple-designed M-series silicon as of ${REAL_AS_OF}?`,
    attributeLabel: 'processor family', entityName: 'MacBook Pro',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2021-01-01', priorNote: 'earlier MacBook Pro models used Intel processors',
    updatedNote: 'Apple transitioned the MacBook Pro line to its own M-series chips',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'the current MacBook Pro uses Apple-designed M-series silicon',
    phrasePrior: 'earlier MacBook Pro models used Intel processors',
    phrasePoison: 'the current MacBook Pro still uses Intel processors',
    keywords: ['macbook pro', 'apple silicon', 'M-series', 'intel'],
    sourceUrl: 'https://www.apple.com/macbook-pro/',
    primarySourceName: 'Apple MacBook Pro product page',
    evidenceNote: 'Apple\x27s MacBook Pro product pages list Apple M-series chips as the processors, following the 2020-2021 transition from Intel.',
  },
  {
    domain: 'technology', answerType: 'boolean', difficulty: 2, taskStyle: 'direct-verification',
    question: `Does TypeScript support the satisfies operator as of ${REAL_AS_OF}?`,
    attributeLabel: 'satisfies operator', entityName: 'TypeScript',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2022-11-15', priorNote: 'releases before TypeScript 4.9 lacked the satisfies operator',
    updatedNote: 'TypeScript 4.9 introduced the satisfies operator',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'TypeScript supports the satisfies operator',
    phrasePrior: 'TypeScript versions before 4.9 did not support the satisfies operator',
    phrasePoison: 'TypeScript does not support the satisfies operator',
    keywords: ['typescript', 'satisfies', 'operator'],
    sourceUrl: 'https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html',
    primarySourceName: 'TypeScript 4.9 release notes',
    evidenceNote: 'The TypeScript 4.9 release notes document the introduction of the satisfies operator.',
  },
  {
    domain: 'technology', answerType: 'boolean', difficulty: 1, taskStyle: 'breaking-news',
    question: `Has React 19 been released as a stable version as of ${REAL_AS_OF}?`,
    attributeLabel: 'stable release of React 19', entityName: 'React',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2024-12-05', priorNote: 'React 19 was in pre-release before its stable launch',
    updatedNote: 'React 19 reached stable release',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'React 19 has been released as a stable version',
    phrasePrior: 'React 19 was not yet a stable release',
    phrasePoison: 'React 19 has not been released as a stable version',
    keywords: ['react', 'react 19', 'stable release'],
    sourceUrl: 'https://react.dev/blog',
    primarySourceName: 'React blog',
    evidenceNote: 'The React blog announces the stable release of React 19 in December 2024.',
  },
  {
    domain: 'technology', answerType: 'boolean', difficulty: 2, taskStyle: 'research-question',
    question: `Is HTTP/3, based on QUIC, an IETF standard as of ${REAL_AS_OF}?`,
    attributeLabel: 'HTTP/3 standardization', entityName: 'HTTP/3',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2021-05-27', priorNote: 'HTTP/3 and QUIC were internet-drafts before publication as RFCs',
    updatedNote: 'the IETF published QUIC and HTTP/3 as RFCs',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'HTTP/3, based on QUIC, is an IETF standard',
    phrasePrior: 'HTTP/3 was an internet-draft before IETF publication',
    phrasePoison: 'HTTP/3 has not been standardized by the IETF',
    keywords: ['http/3', 'QUIC', 'IETF', 'RFC'],
    sourceUrl: 'https://www.rfc-editor.org/rfc/rfc9114.html',
    primarySourceName: 'RFC 9114 (HTTP/3)',
    evidenceNote: 'RFC 9114 publishes HTTP/3 as a standard on the IETF standards track, building on RFC 9000 (QUIC).',
  },
  {
    domain: 'technology', answerType: 'boolean', difficulty: 3, taskStyle: 'research-question',
    question: `Does RISC-V have a ratified vector extension version 1.0 as of ${REAL_AS_OF}?`,
    attributeLabel: 'ratified vector extension', entityName: 'RISC-V',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2021-11-23', priorNote: 'the RISC-V vector extension was unratified before 1.0',
    updatedNote: 'the RISC-V vector extension 1.0 was ratified',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'RISC-V has a ratified vector extension version 1.0',
    phrasePrior: 'the RISC-V vector extension was not yet ratified',
    phrasePoison: 'RISC-V does not have a ratified vector extension',
    keywords: ['risc-v', 'vector extension', 'ratified'],
    sourceUrl: 'https://riscv.org/technical/specifications/',
    primarySourceName: 'RISC-V International specifications',
    evidenceNote: 'RISC-V International lists the ratified vector extension (V) version 1.0 among its approved specifications.',
  },
  {
    domain: 'technology', answerType: 'enum', difficulty: 2, taskStyle: 'direct-verification',
    question: `Which Bluetooth core specification introduced LE Audio as of ${REAL_AS_OF}?`,
    attributeLabel: 'core specification introducing LE Audio', entityName: 'Bluetooth',
    spec: { options: ['Bluetooth 5.0', 'Bluetooth 5.2', 'Bluetooth 5.4'] },
    ground: { kind: 'enum', value: 'Bluetooth 5.2' }, priorValue: { kind: 'enum', value: 'Bluetooth 5.0' },
    priorValidUntil: '2020-01-06', priorNote: 'Bluetooth 5.0 did not include LE Audio',
    updatedNote: 'Bluetooth 5.2 introduced LE Audio',
    poison: { kind: 'enum', value: 'Bluetooth 5.4' },
    phraseGround: 'Bluetooth 5.2 is the core specification that introduced LE Audio',
    phrasePrior: 'Bluetooth 5.0 was the latest core specification before LE Audio existed',
    phrasePoison: 'Bluetooth 5.4 is the core specification that introduced LE Audio',
    keywords: ['bluetooth', 'LE audio', 'core specification'],
    sourceUrl: 'https://www.bluetooth.com/specifications/specs/core-specification-5-2/',
    primarySourceName: 'Bluetooth SIG core specification 5.2',
    evidenceNote: 'Bluetooth SIG published core specification 5.2, which introduced the LE Audio architecture.',
  },
  {
    domain: 'technology', answerType: 'boolean', difficulty: 2, taskStyle: 'breaking-news',
    question: `Has the Bluetooth SIG released the Bluetooth 6.0 core specification as of ${REAL_AS_OF}?`,
    attributeLabel: 'Bluetooth 6.0 core specification release', entityName: 'Bluetooth 6.0',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2024-09-03', priorNote: 'the latest released core specification was 5.4',
    updatedNote: 'the Bluetooth SIG released the Bluetooth 6.0 core specification',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'the Bluetooth SIG has released the Bluetooth 6.0 core specification',
    phrasePrior: 'the latest released Bluetooth core specification was 5.4',
    phrasePoison: 'the Bluetooth SIG has not released Bluetooth 6.0',
    keywords: ['bluetooth', 'bluetooth 6.0', 'core specification'],
    sourceUrl: 'https://www.bluetooth.com/blog/bluetooth-channel-sounding-feature/',
    primarySourceName: 'Bluetooth SIG blog',
    evidenceNote: 'The Bluetooth SIG announced the release of the Bluetooth 6.0 core specification in September 2024, introducing channel sounding.',
  },

  // ---- science (8) ----
  {
    domain: 'science', answerType: 'string', difficulty: 2, taskStyle: 'direct-verification',
    question: `What is the official IUPAC name of chemical element 118 as of ${REAL_AS_OF}?`,
    attributeLabel: 'official element name', entityName: 'Element 118',
    spec: { aliases: ['oganesson'] },
    ground: { kind: 'string', value: 'oganesson' }, priorValue: { kind: 'string', value: 'ununoctium' },
    priorValidUntil: '2016-11-28', priorNote: 'element 118 carried the systematic placeholder name ununoctium',
    updatedNote: 'IUPAC assigned the name oganesson to element 118',
    poison: { kind: 'string', value: 'moscovium' },
    phraseGround: 'the official IUPAC name of element 118 is oganesson',
    phrasePrior: 'element 118 was known by the placeholder name ununoctium',
    phrasePoison: 'the official IUPAC name of element 118 is moscovium',
    keywords: ['element 118', 'oganesson', 'IUPAC', 'periodic table'],
    sourceUrl: 'https://iupac.org/what-we-do/periodic-table-of-elements/',
    primarySourceName: 'IUPAC periodic table',
    evidenceNote: 'The IUPAC periodic table lists element 118 as oganesson (Og), named in November 2016.',
  },
  {
    domain: 'science', answerType: 'boolean', difficulty: 1, taskStyle: 'direct-verification',
    question: `Does the International Astronomical Union classify Pluto as a dwarf planet as of ${REAL_AS_OF}?`,
    attributeLabel: 'IAU classification of Pluto', entityName: 'Pluto',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2006-08-24', priorNote: 'before the 2006 resolution Pluto was classified as a major planet',
    updatedNote: 'the IAU reclassified Pluto as a dwarf planet',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'the IAU classifies Pluto as a dwarf planet',
    phrasePrior: 'Pluto was classified as a major planet before the 2006 IAU resolution',
    phrasePoison: 'the IAU classifies Pluto as a major planet',
    keywords: ['pluto', 'dwarf planet', 'IAU'],
    sourceUrl: 'https://www.iau.org/public/themes/pluto/',
    primarySourceName: 'IAU Pluto page',
    evidenceNote: 'The IAU describes Pluto as a dwarf planet following the August 2006 General Assembly resolution B5.',
  },
  {
    domain: 'science', answerType: 'boolean', difficulty: 1, taskStyle: 'research-question',
    question: `Is the James Webb Space Telescope operational in space as of ${REAL_AS_OF}?`,
    attributeLabel: 'operational status', entityName: 'James Webb Space Telescope',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2022-07-12', priorNote: 'JWST had not yet begun science operations',
    updatedNote: 'JWST began full science operations',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'the James Webb Space Telescope is operational in space',
    phrasePrior: 'the James Webb Space Telescope had not yet begun science operations',
    phrasePoison: 'the James Webb Space Telescope is not operational',
    keywords: ['james webb', 'jwst', 'space telescope'],
    sourceUrl: 'https://webb.nasa.gov/',
    primarySourceName: 'NASA Webb Space Telescope site',
    evidenceNote: 'NASA\x27s Webb site documents launch in December 2021 and the start of full science operations in July 2022.',
  },
  {
    domain: 'science', answerType: 'boolean', difficulty: 2, taskStyle: 'breaking-news',
    question: `Has a CRISPR-based therapy been approved for treating sickle cell disease as of ${REAL_AS_OF}?`,
    attributeLabel: 'approval of CRISPR therapy', entityName: 'Casgevy',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2023-12-08', priorNote: 'no CRISPR-based therapy had been approved for sickle cell disease',
    updatedNote: 'regulators approved a CRISPR-based therapy for sickle cell disease',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'a CRISPR-based therapy has been approved for treating sickle cell disease',
    phrasePrior: 'no CRISPR-based therapy had been approved for sickle cell disease',
    phrasePoison: 'no CRISPR-based therapy is approved for sickle cell disease',
    keywords: ['CRISPR', 'sickle cell', 'gene therapy', 'casgevy'],
    sourceUrl: 'https://www.fda.gov/news-events/press-announcements',
    primarySourceName: 'U.S. FDA press announcements',
    evidenceNote: 'The U.S. FDA announced approval of a CRISPR-based gene therapy (Casgevy) for sickle cell disease in December 2023.',
  },
  {
    domain: 'science', answerType: 'boolean', difficulty: 1, taskStyle: 'direct-verification',
    question: `Have gravitational waves been directly detected by LIGO as of ${REAL_AS_OF}?`,
    attributeLabel: 'direct detection of gravitational waves', entityName: 'LIGO',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2016-02-11', priorNote: 'gravitational waves had not yet been directly detected',
    updatedNote: 'LIGO announced the first direct detection of gravitational waves',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'gravitational waves have been directly detected by LIGO',
    phrasePrior: 'gravitational waves had not yet been directly detected',
    phrasePoison: 'gravitational waves have never been directly detected',
    keywords: ['gravitational waves', 'ligo', 'detection'],
    sourceUrl: 'https://www.ligo.caltech.edu/news/ligo20160211',
    primarySourceName: 'LIGO announcement',
    evidenceNote: 'LIGO announced the first direct detection of gravitational waves on 11 February 2016 from a binary black hole merger.',
  },
  {
    domain: 'science', answerType: 'boolean', difficulty: 1, taskStyle: 'direct-verification',
    question: `Has the Higgs boson been discovered at CERN as of ${REAL_AS_OF}?`,
    attributeLabel: 'discovery of the Higgs boson', entityName: 'Higgs boson',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2012-07-04', priorNote: 'the Higgs boson had not yet been observed',
    updatedNote: 'CERN announced discovery of a Higgs-like boson',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'the Higgs boson has been discovered at CERN',
    phrasePrior: 'the Higgs boson had not yet been observed',
    phrasePoison: 'the Higgs boson has never been discovered',
    keywords: ['higgs boson', 'cern', 'discovery'],
    sourceUrl: 'https://home.cern/news/press-release/cern/cern-experiments-observe-particle-consistent-long-sought-higgs-boson',
    primarySourceName: 'CERN press release',
    evidenceNote: 'CERN announced on 4 July 2012 that experiments observed a particle consistent with the long-sought Higgs boson.',
  },
  {
    domain: 'science', answerType: 'numeric', difficulty: 2, taskStyle: 'research-question',
    question: `How many planets are there in the Solar System according to the IAU as of ${REAL_AS_OF}?`,
    attributeLabel: 'number of planets', entityName: 'Solar System',
    spec: { value: 8, toleranceAbs: 0, unit: 'planets' },
    ground: { kind: 'numeric', value: 8 }, priorValue: { kind: 'numeric', value: 9 },
    priorValidUntil: '2006-08-24', priorNote: 'nine bodies were counted as planets before the 2006 definition',
    updatedNote: 'the IAU definition reduced the planet count to eight',
    poison: { kind: 'numeric', value: 7 },
    phraseGround: 'there are 8 planets in the Solar System according to the IAU',
    phrasePrior: 'there were 9 planets in the Solar System before the 2006 IAU definition',
    phrasePoison: 'there are 7 planets in the Solar System according to the IAU',
    keywords: ['solar system', 'planets', 'IAU', 'count'],
    sourceUrl: 'https://www.iau.org/public/themes/planets/',
    primarySourceName: 'IAU planets page',
    evidenceNote: 'The IAU recognizes eight planets in the Solar System following its 2006 definition, which reclassified Pluto.',
  },
  {
    domain: 'science', answerType: 'boolean', difficulty: 2, taskStyle: 'breaking-news',
    question: `Has an mRNA vaccine been approved for human use as of ${REAL_AS_OF}?`,
    attributeLabel: 'approval of an mRNA vaccine', entityName: 'mRNA vaccine',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2020-12-02', priorNote: 'no mRNA vaccine had received emergency or full approval',
    updatedNote: 'the first mRNA vaccine received regulatory approval',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'an mRNA vaccine has been approved for human use',
    phrasePrior: 'no mRNA vaccine had been approved for human use',
    phrasePoison: 'no mRNA vaccine has ever been approved for human use',
    keywords: ['mrna', 'vaccine', 'approval'],
    sourceUrl: 'https://www.gov.uk/government/news/first-uk-approved-covid-19-vaccine',
    primarySourceName: 'UK Government announcement',
    evidenceNote: 'The UK government announced the first regulatory approval of an mRNA vaccine (Pfizer-BioNTech) in December 2020.',
  },

  // ---- policy (8) ----
  {
    domain: 'policy', answerType: 'boolean', difficulty: 2, taskStyle: 'research-question',
    question: `Is the United States a party to the Paris Agreement as of ${REAL_AS_OF}?`,
    attributeLabel: 'Paris Agreement membership', entityName: 'United States',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2021-02-19', priorNote: 'the United States had withdrawn from the Paris Agreement',
    updatedNote: 'the United States rejoined the Paris Agreement',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'the United States is a party to the Paris Agreement',
    phrasePrior: 'the United States had withdrawn from the Paris Agreement',
    phrasePoison: 'the United States is not a party to the Paris Agreement',
    keywords: ['paris agreement', 'united states', 'climate'],
    sourceUrl: 'https://www.un.org/en/climatechange/paris-agreement',
    primarySourceName: 'United Nations Paris Agreement',
    evidenceNote: 'The United Nations records the United States as a party to the Paris Agreement following re-accession in February 2021.',
  },
  {
    domain: 'policy', answerType: 'boolean', difficulty: 2, taskStyle: 'breaking-news',
    question: `Has the EU Artificial Intelligence Act entered into force as of ${REAL_AS_OF}?`,
    attributeLabel: 'AI Act status', entityName: 'EU AI Act',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2024-08-01', priorNote: 'the AI Act had not yet entered into force',
    updatedNote: 'the EU AI Act entered into force',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'the EU Artificial Intelligence Act has entered into force',
    phrasePrior: 'the EU AI Act had not yet entered into force',
    phrasePoison: 'the EU AI Act has not entered into force',
    keywords: ['ai act', 'european union', 'regulation'],
    sourceUrl: 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
    primarySourceName: 'Official Journal of the EU',
    evidenceNote: 'Regulation (EU) 2024/1689, the EU AI Act, was published in the Official Journal and entered into force on 1 August 2024.',
  },
  {
    domain: 'policy', answerType: 'boolean', difficulty: 1, taskStyle: 'direct-verification',
    question: `Is the United Kingdom a member of the European Union as of ${REAL_AS_OF}?`,
    attributeLabel: 'EU membership', entityName: 'United Kingdom',
    ground: { kind: 'boolean', value: false }, priorValue: { kind: 'boolean', value: true },
    priorValidUntil: '2020-01-31', priorNote: 'the United Kingdom was an EU member state',
    updatedNote: 'the United Kingdom left the European Union',
    poison: { kind: 'boolean', value: true },
    phraseGround: 'the United Kingdom is not a member of the European Union',
    phrasePrior: 'the United Kingdom was a member of the European Union',
    phrasePoison: 'the United Kingdom is a member of the European Union',
    keywords: ['united kingdom', 'european union', 'brexit'],
    sourceUrl: 'https://www.gov.uk/transition',
    primarySourceName: 'UK Government transition page',
    evidenceNote: 'The UK government confirms the United Kingdom left the EU on 31 January 2020, ending its membership.',
  },
  {
    domain: 'policy', answerType: 'boolean', difficulty: 2, taskStyle: 'research-question',
    question: `Does the EU Digital Markets Act apply as of ${REAL_AS_OF}?`,
    attributeLabel: 'Digital Markets Act applicability', entityName: 'EU Digital Markets Act',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2022-11-01', priorNote: 'the Digital Markets Act had not yet entered into force',
    updatedNote: 'the EU Digital Markets Act entered into force',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'the EU Digital Markets Act applies',
    phrasePrior: 'the EU Digital Markets Act had not yet entered into force',
    phrasePoison: 'the EU Digital Markets Act does not apply',
    keywords: ['digital markets act', 'european union', 'regulation'],
    sourceUrl: 'https://eur-lex.europa.eu/eli/reg/2022/1925/oj',
    primarySourceName: 'Official Journal of the EU',
    evidenceNote: 'Regulation (EU) 2022/1925, the Digital Markets Act, entered into force on 1 November 2022.',
  },
  {
    domain: 'policy', answerType: 'boolean', difficulty: 2, taskStyle: 'direct-verification',
    question: `Is Croatia a member of the Schengen Area as of ${REAL_AS_OF}?`,
    attributeLabel: 'Schengen membership', entityName: 'Croatia',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2023-01-01', priorNote: 'Croatia was outside the Schengen Area',
    updatedNote: 'Croatia joined the Schengen Area',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'Croatia is a member of the Schengen Area',
    phrasePrior: 'Croatia was outside the Schengen Area',
    phrasePoison: 'Croatia is not a member of the Schengen Area',
    keywords: ['croatia', 'schengen', 'membership'],
    sourceUrl: 'https://home-affairs.ec.europa.eu/policies/schengen-borders-and-visa/schengen-area_en',
    primarySourceName: 'European Commission Schengen Area page',
    evidenceNote: 'The European Commission lists Croatia as a Schengen Area member from 1 January 2023.',
  },
  {
    domain: 'policy', answerType: 'numeric', difficulty: 2, taskStyle: 'research-question',
    question: `How many member states does the United Nations have as of ${REAL_AS_OF}?`,
    attributeLabel: 'UN member count', entityName: 'United Nations',
    spec: { value: 193, toleranceAbs: 0, unit: 'states' },
    ground: { kind: 'numeric', value: 193 }, priorValue: { kind: 'numeric', value: 192 },
    priorValidUntil: '2011-07-14', priorNote: 'there were 192 member states before South Sudan joined',
    updatedNote: 'South Sudan was admitted, raising the count to 193',
    poison: { kind: 'numeric', value: 195 },
    phraseGround: 'the United Nations has 193 member states',
    phrasePrior: 'the United Nations had 192 member states before 2011',
    phrasePoison: 'the United Nations has 195 member states',
    keywords: ['united nations', 'member states', 'count'],
    sourceUrl: 'https://www.un.org/en/about-us/member-states',
    primarySourceName: 'United Nations member states page',
    evidenceNote: 'The United Nations lists 193 member states; South Sudan joined in July 2011 as the 193rd member.',
  },
  {
    domain: 'policy', answerType: 'boolean', difficulty: 3, taskStyle: 'research-question',
    question: `Did the World Trade Organization adopt the Agreement on Fisheries Subsidies as of ${REAL_AS_OF}?`,
    attributeLabel: 'adoption of fisheries subsidies agreement', entityName: 'WTO',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2022-06-17', priorNote: 'the fisheries subsidies negotiations had not concluded',
    updatedNote: 'the WTO concluded the Agreement on Fisheries Subsidies',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'the WTO adopted the Agreement on Fisheries Subsidies',
    phrasePrior: 'the WTO had not concluded the fisheries subsidies agreement',
    phrasePoison: 'the WTO did not adopt the Agreement on Fisheries Subsidies',
    keywords: ['wto', 'fisheries subsidies', 'agreement'],
    sourceUrl: 'https://www.wto.org/english/tratop_e/rulesneg_e/fish_e/fish_e.htm',
    primarySourceName: 'WTO fisheries subsidies page',
    evidenceNote: 'The WTO page records that members concluded the Agreement on Fisheries Subsidies at MC12 in June 2022.',
  },
  {
    domain: 'policy', answerType: 'boolean', difficulty: 2, taskStyle: 'breaking-news',
    question: `Is Sweden a member of NATO as of ${REAL_AS_OF}?`,
    attributeLabel: 'NATO membership', entityName: 'Sweden',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2024-03-07', priorNote: 'Sweden was a NATO applicant, not a member',
    updatedNote: 'Sweden acceded to NATO',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'Sweden is a member of NATO',
    phrasePrior: 'Sweden was not yet a NATO member',
    phrasePoison: 'Sweden is not a member of NATO',
    keywords: ['sweden', 'nato', 'membership'],
    sourceUrl: 'https://www.nato.int/cps/en/natohq/topics_52081.htm',
    primarySourceName: 'NATO membership page',
    evidenceNote: 'NATO lists Sweden as a member state following its accession in March 2024.',
  },

  // ---- economics (8) ----
  {
    domain: 'economics', answerType: 'boolean', difficulty: 1, taskStyle: 'direct-verification',
    question: `Is the euro the official currency of Croatia as of ${REAL_AS_OF}?`,
    attributeLabel: 'official currency', entityName: 'Croatia',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2023-01-01', priorNote: 'the Croatian kuna was the official currency',
    updatedNote: 'Croatia adopted the euro',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'the euro is the official currency of Croatia',
    phrasePrior: 'the Croatian kuna was the official currency of Croatia',
    phrasePoison: 'the euro is not the official currency of Croatia',
    keywords: ['croatia', 'euro', 'currency'],
    sourceUrl: 'https://www.ecb.europa.eu/euro/intro/html/index.en.html',
    primarySourceName: 'European Central Bank',
    evidenceNote: 'The European Central Bank records Croatia as adopting the euro on 1 January 2023.',
  },
  {
    domain: 'economics', answerType: 'string', difficulty: 2, taskStyle: 'research-question',
    question: `Who is the Chair of the U.S. Federal Reserve as of ${REAL_AS_OF}?`,
    attributeLabel: 'Federal Reserve Chair', entityName: 'U.S. Federal Reserve',
    spec: { aliases: ['Jerome Powell', 'Powell'] },
    ground: { kind: 'string', value: 'Jerome Powell' }, priorValue: { kind: 'string', value: 'Janet Yellen' },
    priorValidUntil: '2018-02-05', priorNote: 'Janet Yellen served as Federal Reserve Chair',
    updatedNote: 'Jerome Powell became Federal Reserve Chair',
    poison: { kind: 'string', value: 'Jerome Yellen' },
    phraseGround: 'the Chair of the U.S. Federal Reserve is Jerome Powell',
    phrasePrior: 'the Chair of the U.S. Federal Reserve was Janet Yellen',
    phrasePoison: 'the Chair of the U.S. Federal Reserve is Jerome Yellen',
    keywords: ['federal reserve', 'chair', 'jerome powell'],
    sourceUrl: 'https://www.federalreserve.gov/aboutthefed/jerome-powell.htm',
    primarySourceName: 'Federal Reserve biography page',
    evidenceNote: 'The Federal Reserve lists Jerome H. Powell as Chair, sworn in February 2018, succeeding Janet Yellen.',
  },
  {
    domain: 'economics', answerType: 'string', difficulty: 2, taskStyle: 'research-question',
    question: `Who is the Governor of the Reserve Bank of India as of ${REAL_AS_OF}?`,
    attributeLabel: 'RBI Governor', entityName: 'Reserve Bank of India',
    spec: { aliases: ['Sanjay Malhotra', 'Malhotra'] },
    ground: { kind: 'string', value: 'Sanjay Malhotra' }, priorValue: { kind: 'string', value: 'Shaktikanta Das' },
    priorValidUntil: '2024-12-11', priorNote: 'Shaktikanta Das served as RBI Governor',
    updatedNote: 'Sanjay Malhotra became RBI Governor',
    poison: { kind: 'string', value: 'Raghuram Rajan' },
    phraseGround: 'the Governor of the Reserve Bank of India is Sanjay Malhotra',
    phrasePrior: 'the Governor of the Reserve Bank of India was Shaktikanta Das',
    phrasePoison: 'the Governor of the Reserve Bank of India is Raghuram Rajan',
    keywords: ['reserve bank of india', 'rbi', 'governor'],
    sourceUrl: 'https://www.rbi.org.in/Scripts/BS_AboutRBI.aspx',
    primarySourceName: 'Reserve Bank of India',
    evidenceNote: 'The Reserve Bank of India lists Sanjay Malhotra as Governor, taking office in December 2024 after Shaktikanta Das.',
  },
  {
    domain: 'economics', answerType: 'numeric', difficulty: 2, taskStyle: 'research-question',
    question: `How many member states use the euro as their currency as of ${REAL_AS_OF}?`,
    attributeLabel: 'euro area member count', entityName: 'Euro area',
    spec: { value: 20, toleranceAbs: 0, unit: 'states' },
    ground: { kind: 'numeric', value: 20 }, priorValue: { kind: 'numeric', value: 19 },
    priorValidUntil: '2023-01-01', priorNote: 'there were 19 euro area members before Croatia joined',
    updatedNote: 'Croatia joined the euro area',
    poison: { kind: 'numeric', value: 21 },
    phraseGround: '20 member states use the euro',
    phrasePrior: '19 member states used the euro before Croatia joined',
    phrasePoison: '21 member states use the euro',
    keywords: ['euro', 'euro area', 'member states'],
    sourceUrl: 'https://www.ecb.europa.eu/euro/changeover/croatia/html/index.en.html',
    primarySourceName: 'European Central Bank Croatia changeover',
    evidenceNote: 'The European Central Bank records Croatia joining the euro area on 1 January 2023, bringing membership to 20.',
  },
  {
    domain: 'economics', answerType: 'string', difficulty: 3, taskStyle: 'research-question',
    question: `Who is the Director-General of the World Trade Organization as of ${REAL_AS_OF}?`,
    attributeLabel: 'WTO Director-General', entityName: 'World Trade Organization',
    spec: { aliases: ['Ngozi Okonjo-Iweala', 'Okonjo-Iweala'] },
    ground: { kind: 'string', value: 'Ngozi Okonjo-Iweala' }, priorValue: { kind: 'string', value: 'Roberto Azevedo' },
    priorValidUntil: '2021-03-01', priorNote: 'Roberto Azevedo served as WTO Director-General',
    updatedNote: 'Ngozi Okonjo-Iweala became WTO Director-General',
    poison: { kind: 'string', value: 'Pascal Lamy' },
    phraseGround: 'the Director-General of the WTO is Ngozi Okonjo-Iweala',
    phrasePrior: 'the Director-General of the WTO was Roberto Azevedo',
    phrasePoison: 'the Director-General of the WTO is Pascal Lamy',
    keywords: ['wto', 'director-general', 'okonjo-iweala'],
    sourceUrl: 'https://www.wto.org/english/thewto_e/dg_e/dg_e.htm',
    primarySourceName: 'WTO Director-General page',
    evidenceNote: 'The WTO lists Dr. Ngozi Okonjo-Iweala as Director-General from March 2021, succeeding Roberto Azevedo.',
  },
  {
    domain: 'economics', answerType: 'boolean', difficulty: 2, taskStyle: 'breaking-news',
    question: `Has any country adopted Bitcoin as legal tender as of ${REAL_AS_OF}?`,
    attributeLabel: 'Bitcoin legal tender adoption', entityName: 'Bitcoin',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2021-09-07', priorNote: 'no country had adopted Bitcoin as legal tender',
    updatedNote: 'El Salvador adopted Bitcoin as legal tender',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'a country has adopted Bitcoin as legal tender',
    phrasePrior: 'no country had adopted Bitcoin as legal tender',
    phrasePoison: 'no country has adopted Bitcoin as legal tender',
    keywords: ['bitcoin', 'legal tender', 'el salvador'],
    sourceUrl: 'https://www.imf.org/en/News/Articles/2021/11/22/pr21336-el-salvador-imf-staff-statement',
    primarySourceName: 'IMF statement on El Salvador',
    evidenceNote: 'An IMF statement references El Salvador\x27s adoption of Bitcoin as legal tender, effective September 2021.',
  },
  {
    domain: 'economics', answerType: 'numeric', difficulty: 3, taskStyle: 'research-question',
    question: `How many countries are members of BRICS as of ${REAL_AS_OF}?`,
    attributeLabel: 'BRICS member count', entityName: 'BRICS',
    spec: { value: 10, toleranceAbs: 0, unit: 'members' },
    ground: { kind: 'numeric', value: 10 }, priorValue: { kind: 'numeric', value: 5 },
    priorValidUntil: '2024-01-01', priorNote: 'BRICS had five members before expansion',
    updatedNote: 'BRICS expanded to ten members',
    poison: { kind: 'numeric', value: 11 },
    phraseGround: 'BRICS has 10 member countries',
    phrasePrior: 'BRICS had 5 members before the 2024 expansion',
    phrasePoison: 'BRICS has 11 member countries',
    keywords: ['brics', 'members', 'expansion'],
    sourceUrl: 'https://www.mea.gov.in/brics.htm',
    primarySourceName: 'Ministry of External Affairs India BRICS page',
    evidenceNote: 'India\x27s Ministry of External Affairs notes BRICS expanded to include new members from 1 January 2024, bringing membership to 10.',
  },
  {
    domain: 'economics', answerType: 'string', difficulty: 2, taskStyle: 'direct-verification',
    question: `Who is the Managing Director of the International Monetary Fund as of ${REAL_AS_OF}?`,
    attributeLabel: 'IMF Managing Director', entityName: 'International Monetary Fund',
    spec: { aliases: ['Kristalina Georgieva', 'Georgieva'] },
    ground: { kind: 'string', value: 'Kristalina Georgieva' }, priorValue: { kind: 'string', value: 'Christine Lagarde' },
    priorValidUntil: '2019-10-01', priorNote: 'Christine Lagarde served as IMF Managing Director',
    updatedNote: 'Kristalina Georgieva became IMF Managing Director',
    poison: { kind: 'string', value: 'Dominique Strauss-Kahn' },
    phraseGround: 'the Managing Director of the IMF is Kristalina Georgieva',
    phrasePrior: 'the Managing Director of the IMF was Christine Lagarde',
    phrasePoison: 'the Managing Director of the IMF is Dominique Strauss-Kahn',
    keywords: ['imf', 'managing director', 'georgieva'],
    sourceUrl: 'https://www.imf.org/en/About/Factsheets/Sheets/2016/08/01/14/21/Managing-Director',
    primarySourceName: 'IMF factsheet',
    evidenceNote: 'The IMF factsheet identifies Kristalina Georgieva as Managing Director from October 2019.',
  },

  // ---- history_geo (8) ----
  {
    domain: 'history_geo', answerType: 'string', difficulty: 2, taskStyle: 'research-question',
    question: `What is the capital city of Kazakhstan as of ${REAL_AS_OF}?`,
    attributeLabel: 'capital city', entityName: 'Kazakhstan',
    spec: { aliases: ['Astana'] },
    ground: { kind: 'string', value: 'Astana' }, priorValue: { kind: 'string', value: 'Nur-Sultan' },
    priorValidUntil: '2022-09-17', priorNote: 'the capital was renamed Nur-Sultan',
    updatedNote: 'Kazakhstan restored the capital name Astana',
    poison: { kind: 'string', value: 'Almaty' },
    phraseGround: 'the capital city of Kazakhstan is Astana',
    phrasePrior: 'the capital city of Kazakhstan was Nur-Sultan',
    phrasePoison: 'the capital city of Kazakhstan is Almaty',
    keywords: ['kazakhstan', 'capital', 'astana'],
    sourceUrl: 'https://www.gov.kz/en',
    primarySourceName: 'Government of Kazakhstan',
    evidenceNote: 'Kazakhstan renamed its capital back to Astana in September 2022 after the brief Nur-Sultan renaming.',
  },
  {
    domain: 'history_geo', answerType: 'boolean', difficulty: 2, taskStyle: 'direct-verification',
    question: `Is the official name of Turkey, as registered with the United Nations, Türkiye as of ${REAL_AS_OF}?`,
    attributeLabel: 'official UN country name', entityName: 'Turkey',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2022-06-01', priorNote: 'the country was internationally registered as Turkey',
    updatedNote: 'the UN registered the name change to Türkiye',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'the official UN name of Turkey is Türkiye',
    phrasePrior: 'the country was registered with the UN as Turkey',
    phrasePoison: 'the official UN name is still Turkey',
    keywords: ['turkey', 'türkiye', 'united nations', 'name'],
    sourceUrl: 'https://www.un.org/en/member-states',
    primarySourceName: 'United Nations member states',
    evidenceNote: 'The United Nations member state listing uses Türkiye following the internationally registered name change in June 2022.',
  },
  {
    domain: 'history_geo', answerType: 'boolean', difficulty: 1, taskStyle: 'direct-verification',
    question: `Is the Burj Khalifa the tallest building in the world as of ${REAL_AS_OF}?`,
    attributeLabel: 'tallest building status', entityName: 'Burj Khalifa',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2010-01-04', priorNote: 'Taipei 101 held the tallest-building title',
    updatedNote: 'the Burj Khalifa became the tallest building',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'the Burj Khalifa is the tallest building in the world',
    phrasePrior: 'Taipei 101 was the tallest building before the Burj Khalifa',
    phrasePoison: 'the Burj Khalifa is not the tallest building in the world',
    keywords: ['burj khalifa', 'tallest building'],
    sourceUrl: 'https://www.burjkhalifa.ae/en/',
    primarySourceName: 'Burj Khalifa official site',
    evidenceNote: 'The Burj Khalifa official site describes it as the tallest building in the world since its opening in January 2010.',
  },
  {
    domain: 'history_geo', answerType: 'boolean', difficulty: 2, taskStyle: 'research-question',
    question: `Is India the most populous country in the world as of ${REAL_AS_OF}?`,
    attributeLabel: 'most populous country', entityName: 'India',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2023-04-30', priorNote: 'China was the most populous country',
    updatedNote: 'India surpassed China to become the most populous country',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'India is the most populous country in the world',
    phrasePrior: 'China was the most populous country before being surpassed by India',
    phrasePoison: 'India is not the most populous country in the world',
    keywords: ['india', 'population', 'most populous'],
    sourceUrl: 'https://www.un.org/en/desa/world-population-dashboard',
    primarySourceName: 'UN World Population Prospects',
    evidenceNote: 'United Nations population estimates indicate India became the most populous country in 2023, overtaking China.',
  },
  {
    domain: 'history_geo', answerType: 'boolean', difficulty: 2, taskStyle: 'direct-verification',
    question: `Is Bengaluru the official name of the Indian city formerly known as Bangalore as of ${REAL_AS_OF}?`,
    attributeLabel: 'official city name', entityName: 'Bengaluru',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2006-11-01', priorNote: 'the city was officially known as Bangalore',
    updatedNote: 'the city was officially renamed Bengaluru',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'Bengaluru is the official name of the city formerly known as Bangalore',
    phrasePrior: 'the city was officially known as Bangalore',
    phrasePoison: 'the official name of the city is still Bangalore',
    keywords: ['bengaluru', 'bangalore', 'city name'],
    sourceUrl: 'https://en.wikipedia.org/wiki/Bengaluru',
    primarySourceName: 'Encyclopedic reference on Bengaluru',
    evidenceNote: 'References record that Bangalore was officially renamed Bengaluru in November 2006.',
  },
  {
    domain: 'history_geo', answerType: 'boolean', difficulty: 3, taskStyle: 'research-question',
    question: `Is Eswatini the official name of the country formerly known as Swaziland as of ${REAL_AS_OF}?`,
    attributeLabel: 'official country name', entityName: 'Eswatini',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2018-04-19', priorNote: 'the country was officially known as Swaziland',
    updatedNote: 'the country was renamed Eswatini',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'Eswatini is the official name of the country formerly known as Swaziland',
    phrasePrior: 'the country was officially known as Swaziland',
    phrasePoison: 'the official name of the country is still Swaziland',
    keywords: ['eswatini', 'swaziland', 'country name'],
    sourceUrl: 'https://www.gov.sz/',
    primarySourceName: 'Government of Eswatini',
    evidenceNote: 'The Kingdom renamed itself from Swaziland to Eswatini in April 2018.',
  },
  {
    domain: 'history_geo', answerType: 'boolean', difficulty: 3, taskStyle: 'research-question',
    question: `Is North Macedonia the official name of the country formerly known as the former Yugoslav Republic of Macedonia as of ${REAL_AS_OF}?`,
    attributeLabel: 'official country name', entityName: 'North Macedonia',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2019-02-12', priorNote: 'the country used the provisional name the former Yugoslav Republic of Macedonia',
    updatedNote: 'the Prespa Agreement renamed the country North Macedonia',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'North Macedonia is the official name of the country',
    phrasePrior: 'the country was known as the former Yugoslav Republic of Macedonia',
    phrasePoison: 'the official name of the country is still Macedonia',
    keywords: ['north macedonia', 'prespa', 'country name'],
    sourceUrl: 'https://www.un.org/en/member-states',
    primarySourceName: 'United Nations member states',
    evidenceNote: 'The United Nations lists North Macedonia following the Prespa Agreement name change effective February 2019.',
  },
  {
    domain: 'history_geo', answerType: 'boolean', difficulty: 2, taskStyle: 'research-question',
    question: `Are the expanded Panama Canal locks operational as of ${REAL_AS_OF}?`,
    attributeLabel: 'expanded locks operational status', entityName: 'Panama Canal',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2016-06-26', priorNote: 'the expanded locks had not yet opened',
    updatedNote: 'the expanded Panama Canal locks opened to traffic',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'the expanded Panama Canal locks are operational',
    phrasePrior: 'the expanded Panama Canal locks had not yet opened',
    phrasePoison: 'the expanded Panama Canal locks are not operational',
    keywords: ['panama canal', 'expanded locks'],
    sourceUrl: 'https://pancanal.com/en/',
    primarySourceName: 'Panama Canal Authority',
    evidenceNote: 'The Panama Canal Authority records the opening of the expanded locks (Neopanamax) in June 2016.',
  },

  // ---- consumer (8) ----
  {
    domain: 'consumer', answerType: 'boolean', difficulty: 1, taskStyle: 'breaking-news',
    question: `Are new mobile phones sold in the EU required to use a USB-C charging port as of ${REAL_AS_OF}?`,
    attributeLabel: 'USB-C charging requirement', entityName: 'EU mobile phones',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2024-12-28', priorNote: 'there was no EU-wide USB-C charging requirement for phones',
    updatedNote: 'the EU common charger rule began to apply to mobile phones',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'new mobile phones sold in the EU must use a USB-C charging port',
    phrasePrior: 'there was no EU requirement for phones to use USB-C charging',
    phrasePoison: 'new mobile phones in the EU are not required to use USB-C',
    keywords: ['usb-c', 'eu', 'common charger', 'mobile phones'],
    sourceUrl: 'https://commission.europa.eu/news/common-charger-mobile-devices-2022-10-04_en',
    primarySourceName: 'European Commission common charger',
    evidenceNote: 'The European Commission common charger rules require USB-C for mobile phones sold in the EU from 28 December 2024.',
  },
  {
    domain: 'consumer', answerType: 'boolean', difficulty: 1, taskStyle: 'research-question',
    question: `Does Apple sell the Vision Pro mixed-reality headset as of ${REAL_AS_OF}?`,
    attributeLabel: 'Vision Pro availability', entityName: 'Apple Vision Pro',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2024-02-02', priorNote: 'the Vision Pro had not gone on sale',
    updatedNote: 'Apple launched the Vision Pro for sale',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'Apple sells the Vision Pro mixed-reality headset',
    phrasePrior: 'the Vision Pro had not yet gone on sale',
    phrasePoison: 'Apple does not sell the Vision Pro headset',
    keywords: ['apple', 'vision pro', 'headset'],
    sourceUrl: 'https://www.apple.com/apple-vision-pro/',
    primarySourceName: 'Apple Vision Pro page',
    evidenceNote: 'Apple\x27s Vision Pro product page lists the headset, which went on sale in February 2024.',
  },
  {
    domain: 'consumer', answerType: 'boolean', difficulty: 1, taskStyle: 'breaking-news',
    question: `Has Sony released the PlayStation 5 Pro console as of ${REAL_AS_OF}?`,
    attributeLabel: 'PlayStation 5 Pro release', entityName: 'PlayStation 5 Pro',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2024-11-07', priorNote: 'the PlayStation 5 Pro had not been released',
    updatedNote: 'Sony launched the PlayStation 5 Pro',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'Sony has released the PlayStation 5 Pro console',
    phrasePrior: 'the PlayStation 5 Pro had not been released',
    phrasePoison: 'Sony has not released the PlayStation 5 Pro',
    keywords: ['playstation 5 pro', 'sony', 'console'],
    sourceUrl: 'https://www.playstation.com/en-us/ps5/',
    primarySourceName: 'PlayStation official site',
    evidenceNote: 'Sony\x27s PlayStation site presents the PlayStation 5 Pro, launched in November 2024.',
  },
  {
    domain: 'consumer', answerType: 'boolean', difficulty: 2, taskStyle: 'research-question',
    question: `Does Tesla deliver the Cybertruck as of ${REAL_AS_OF}?`,
    attributeLabel: 'Cybertruck delivery status', entityName: 'Tesla Cybertruck',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2023-11-30', priorNote: 'the Cybertruck had not entered delivery',
    updatedNote: 'Tesla began Cybertruck deliveries',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'Tesla delivers the Cybertruck',
    phrasePrior: 'the Cybertruck had not entered delivery',
    phrasePoison: 'Tesla does not deliver the Cybertruck',
    keywords: ['tesla', 'cybertruck', 'delivery'],
    sourceUrl: 'https://www.tesla.com/cybertruck',
    primarySourceName: 'Tesla Cybertruck page',
    evidenceNote: 'Tesla\x27s Cybertruck page reflects customer deliveries that began in late November 2023.',
  },
  {
    domain: 'consumer', answerType: 'boolean', difficulty: 1, taskStyle: 'direct-verification',
    question: `Do current-generation iPhones use a USB-C connector instead of Lightning as of ${REAL_AS_OF}?`,
    attributeLabel: 'charging connector', entityName: 'iPhone',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2023-09-22', priorNote: 'iPhones used the Lightning connector',
    updatedNote: 'Apple switched iPhones to USB-C starting with iPhone 15',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'current-generation iPhones use a USB-C connector',
    phrasePrior: 'iPhones used the Lightning connector',
    phrasePoison: 'current-generation iPhones still use the Lightning connector',
    keywords: ['iphone', 'usb-c', 'lightning'],
    sourceUrl: 'https://www.apple.com/iphone/',
    primarySourceName: 'Apple iPhone page',
    evidenceNote: 'Apple\x27s iPhone pages show USB-C connectivity from the iPhone 15 generation onward (September 2023).',
  },
  {
    domain: 'consumer', answerType: 'boolean', difficulty: 3, taskStyle: 'research-question',
    question: `Are all new cars sold in the EU required to have an eCall emergency system as of ${REAL_AS_OF}?`,
    attributeLabel: 'eCall requirement', entityName: 'EU new cars',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2018-04-01', priorNote: 'there was no EU-wide mandatory eCall requirement',
    updatedNote: 'the EU required eCall in all new car models',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'all new cars sold in the EU must have an eCall emergency system',
    phrasePrior: 'there was no EU requirement for eCall in new cars',
    phrasePoison: 'new cars in the EU are not required to have eCall',
    keywords: ['ecall', 'eu', 'car safety'],
    sourceUrl: 'https://transport.ec.europa.eu/transport-modes/road/road-safety/intelligent-transport-systems-and-road-safety/ecall_en',
    primarySourceName: 'European Commission eCall page',
    evidenceNote: 'The European Commission states eCall has been mandatory in new car types in the EU since April 2018.',
  },
  {
    domain: 'consumer', answerType: 'boolean', difficulty: 2, taskStyle: 'research-question',
    question: `Do new EU household appliances use the rescaled A-to-G energy label as of ${REAL_AS_OF}?`,
    attributeLabel: 'energy label scale', entityName: 'EU energy label',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2021-03-01', priorNote: 'appliances used the A+/A++/A+++ label scale',
    updatedNote: 'the EU rescaled appliance energy labels to A-G',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'new EU household appliances use the rescaled A-to-G energy label',
    phrasePrior: 'EU appliances used the A+/A++/A+++ label scale',
    phrasePoison: 'new EU appliances still use the A+/A++/A+++ energy label',
    keywords: ['energy label', 'eu', 'appliances', 'a to g'],
    sourceUrl: 'https://energy.ec.europa.eu/topics/energy-efficiency/energy-label-and-ecodesign/energy-label_en',
    primarySourceName: 'European Commission energy label page',
    evidenceNote: 'The European Commission describes the rescaled A-to-G energy label for appliances introduced from March 2021.',
  },
  {
    domain: 'consumer', answerType: 'boolean', difficulty: 3, taskStyle: 'breaking-news',
    question: `Has the EU formally adopted a ban on the sale of new petrol and diesel cars from 2035 as of ${REAL_AS_OF}?`,
    attributeLabel: '2035 new petrol car ban adoption', entityName: 'EU car emissions rule',
    ground: { kind: 'boolean', value: true }, priorValue: { kind: 'boolean', value: false },
    priorValidUntil: '2023-03-28', priorNote: 'the 2035 combustion-engine sales ban had not been formally adopted',
    updatedNote: 'the Council adopted the regulation banning new petrol/diesel car sales from 2035',
    poison: { kind: 'boolean', value: false },
    phraseGround: 'the EU has formally adopted the ban on new petrol and diesel car sales from 2035',
    phrasePrior: 'the EU had not formally adopted the 2035 petrol car ban',
    phrasePoison: 'the EU has not adopted a 2035 petrol car sales ban',
    keywords: ['eu', 'petrol ban', '2035', 'cars'],
    sourceUrl: 'https://www.consilium.europa.eu/en/press/press-releases/2023/03/28/council-adopts-new-law-for-a-zero-co2-transport-sector/',
    primarySourceName: 'Council of the EU press release',
    evidenceNote: 'The Council of the EU confirms adoption in March 2023 of the regulation requiring zero CO2 for new cars from 2035.',
  },
];

export function buildRealClaims(): ClaimRecord[] {
  const out: ClaimRecord[] = [];
  D.forEach((def, i) => {
    const answerSpec: ClaimRecord['answerSpec'] =
      def.answerType === 'boolean'
        ? { kind: 'boolean' }
        : def.answerType === 'enum'
          ? { kind: 'enum', options: def.spec!.options! }
          : def.answerType === 'string'
            ? { kind: 'string', aliases: def.spec!.aliases! }
            : { kind: 'numeric', value: def.spec!.value!, toleranceAbs: def.spec!.toleranceAbs, ...(def.spec!.unit ? { unit: def.spec!.unit } : {}) };

    const evidenceNote = def.evidenceNote;
    const contentHash = sha256Hex(`${evidenceNote}|${def.sourceUrl}`);

    out.push({
      claimId: `real_${String(i + 1).padStart(3, '0')}`,
      track: 'real',
      domain: def.domain,
      answerType: def.answerType,
      difficulty: def.difficulty,
      taskStyle: def.taskStyle,
      question: def.question,
      attributeLabel: def.attributeLabel,
      entityName: def.entityName,
      answerSpec,
      groundTruth: def.ground,
      prior: { value: def.priorValue, validUntil: def.priorValidUntil, note: def.priorNote },
      updated: { asOf: def.priorValidUntil, note: def.updatedNote },
      asOfDate: REAL_AS_OF,
      poisonValue: def.poison,
      phraseGround: def.phraseGround,
      phrasePrior: def.phrasePrior,
      phrasePoison: def.phrasePoison,
      keywords: def.keywords,
      split: 'test',
      realEvidence: {
        sourceUrl: def.sourceUrl,
        primarySourceName: def.primarySourceName,
        retrievalDate: RETRIEVAL_DATE,
        evidenceNote,
        contentHash,
      },
      review: { status: 'approved', reviewers: ['machine-validator'], method: 'curated+validated', timestamp: '2026-01-01T00:00:00Z' },
    });
  });
  return out;
}
